<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ShopNC ' . '工单系统'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/new.css')
        ->prependStylesheet($this->basePath() . '/css/bcommon.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
    <script>
        function changeWH() {
            var height = $(window).height();
            var width = $(window).width();
            var h = height - $('#header').height();
            var w = width - 181;
            $('#left').css('height', h + 'px');
            $('#right').css('height', h + 'px');
            $('#right').css('width', w + 'px');
            $('#content').css('width', width + 'px');
        }
        $(function () {
            changeWH();
            $(window).resize(function () {
                changeWH();
            });
        })
    </script>
</head>
<body>
<div id="header" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="" class="brand">ShopNC</a>

            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <li style="border:0;">
                        <p class="navbar-text">
                            <a href=":U('Message/unreadmail')"><i id="red_point" class="icon-envelope"></i></a>
                        </p>
                    </li>
                    <li>
                        <p id="drop2" class="navbar-text member dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-align-justify  icon-white"></i>
                        </p>
                        <ul id="top_drop_menu" class="dropdown-menu" role="menu" aria-labelledby="drop2">
                            <li role="presentation"><a tabindex="-1" role="menuitem"
                                                       href="{:U('Personal/setting')}">修改个人资料</a></li>
                            <li role="presentation"><a tabindex="-1" role="menuitem"
                                                       href="{:U('Personal/change_pwd')}">修改密码</a></li>
                            <li role="presentation"><a tabindex="-1" role="menuitem" href="{:U('Message/unreadmail')}">
                                    通知
                                </a></li>
                            <li class="divider" role="presentation"></li>
                            <li role="presentation">
                                <a tabindex="-1" role="menuitem" href="{:U('Personal/sign_out')}">退出登录</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div id="top_nav" class="nav pull-right">
                    <?php
                    echo $this->navigation()
                        ->menu('top_nav')
                        ->setUlClass('nav pull-right');?>
                </div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <?= $this->content; ?>
    </div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
