
<h1>修改密码</h1>

<?php if ($this->error): ?>
    <p class="error">
        发生错误,请看下面提示.
    </p>
<?php endif;?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('admin_personalcenter',array('action'=>'personalChangePassword')));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>

<dl class="zend_form">
    <dt><?php echo $this->formLabel($form->get('old_password')); ?></dt>
    <dd><?php
        echo $this->formElement($form->get('old_password'));
        echo $this->formElementErrors($form->get('old_password'));
        ?></dd>
    <dt><?php echo $this->formLabel($form->get('new_password')); ?></dt>
    <dd><?php
        echo $this->formElement($form->get('new_password'));
        echo $this->formElementErrors($form->get('new_password'));
        ?></dd>
    <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
    <dd><?php
        echo $this->formElement($form->get('confirm_password'));
        echo $this->formElementErrors($form->get('confirm_password'));
        ?></dd>

    <dd><?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?></dd>
</dl>

<?php echo $this->form()->closeTag($form); ?>
