<h1>待审核咨询</h1>
<?php if (count($this->bugs)): ?>
    <table style="width: 700px">
        <tr>
            <th>咨询标题</th>
            <th>咨询分类</th>
            <th>客户名称</th>
            <th>咨询时间</th>
            <th>操作</th>
        </tr>
        <?php foreach ($this->bugs as $item): ?>
            <tr>
                <td><?php echo $item['activeTitle']?></td>
                <td><?php echo $item['className']?></td>
                <td><?php echo $item['memberName']?></td>
                <td><?php echo date('Y-m-d H:i' , $item['insertTime'])?></td>
                <td><a href="<?php echo $this->url('admin_active_examine', array( 'id' => $item['activeId'])); ?>">审核</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination/search.phtml',
    array(
        'route'=>'admin_active_untreated_list'
    )
);?>


