<h1>待审核咨询</h1>
<?php if (count($this->paginator)): ?>
    <table style="width: 700px">
        <tr>
            <th>内容</th>
            <th>发送人</th>
            <th>发送时间</th>
        </tr>
        <?php foreach ($this->paginator as $item): ?>
            <tr>
                <td><?php echo $item['msgContent']?></td>
                <td><?php echo $item['msgFromname']?></td>
                <td><?php echo date('Y-m-d H:i' , $item['insertTime'])?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination/search.phtml',
    array(
        'route'=>'admin_pesonal_personalMessageList'
    )
);?>


