<h3>修改密码</h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">修改密码失败, 请重试.</div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getUsername());

echo $this->form()->openTag($form);

?>

<?php echo $this->formElementErrors($form->get('identity')); ?>
<?php echo $this->formInput($form->get('identity')); ?>
<table>
  <tr>
    <?php $e = $form->get('credential');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php  echo $this->formInput($e);
               echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  <tr>
    <?php $e = $form->get('newCredential');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php  echo $this->formInput($e);
               echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  <tr>
    <?php $e = $form->get('newCredentialVerify');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php  echo $this->formInput($e);
               echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  <tr>
    <?php $e = $form->get('submit');?>
    <td></td>
    <td>
        <?php  echo $this->formInput($e);?>
    </td>
  </tr>
</table>


<?php echo $this->form()->closeTag(); ?>
