<h1>注册</h1>

<?php if ($this->error): ?>
    <p class="error">
                发生错误,请看下面提示.
    </p>
<?php endif;?>
<?php
if (!$this->enableRegistration) {
    print "当前禁止注册, 请联系管理 员.";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->formElement($form->get('type'));echo $this->formElementErrors($form->get('type'));?>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<table>
  <tr>
    <?php $e = $form->get('username');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php  echo $this->formElement($e);
               echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('password');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('passwordVerify');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('email');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php  echo $this->formElement($e);
               echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('realName');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberAddress');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberTelphone');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberPhone');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberQq');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberMsn');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  <tr>
    <?php $e = $form->get('memberWebsite');?>
    <td><?php echo $this->formLabel($e); ?></td>
    <td>
        <?php echo $this->formElement($e);
              echo $this->formElementErrors($e);
        ?>
    </td>
  </tr>
  
  
  
  <tr>
    <?php $e = $form->get('submit');?>
    <td> </td>
    <td>
        <?php echo $this->formElement($e);echo $this->formElementErrors($form->get('submit'));?>
    </td>
  </tr>
  
</table>


        <?php /*if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif */?>
        
<?php echo $this->form()->closeTag() ?>
