<div class="page-header">
    <h4>公海抢单
        <small>(222)</small>
    </h4>
</div>
<br>
<div class="row-fluid">
    <table class="table table-hover">
        <thead>
        <tr class="info table_top">
            <th class="id">编号</th>
            <th class="title">标题</th>
            <th class="requester_id">工单发起人</th>
            <th class="created">任务开始时间</th>
            <th class="group_id">任务结束时间</th>
            <th class="assignee_id">任务抢单截至时间</th>
            <th class="assignee_id">奖励积分</th>
        </tr>

        </thead>
        <tbody>

        <?php foreach ($this->list as $vo): ?>

            <tr>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= $vo['workId'] ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?= $vo['workTitle'] ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?= $vo['serverName'] ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?=date("Y-m-d",$vo['workStarttime']) ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?=date("Y-m-d",$vo['workEndtime'])  ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?=date("Y-m-d H:i", $vo['workJointime']) ?></a>
                </td>
                <td>
                    <a href="{:U('works/info','id='.$vo['works_work_id'])}" class=""><?= $vo['workPoints'] ?></a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<div class="row-fluid">
    {$page}
</div>