<div class="page-header">
    <h4>我的抢单</h4>
</div>
<br>
<div class="row-fluid">
    <table class="table table-hover">
        <thead>
        <tr class="info font-small table_top">
            <th class="id">编号</th>
            <th class="title">标题</th>
            <th class="requester_id">工单发起人</th>
            <th class="created">任务开始时间</th>
            <th class="group_id">任务结束时间</th>
            <th class="group_id">奖励积分</th>
            <th class="assignee_id">任务抢单截至时间</th>
            <th class="assignee_id">任务状态</th>

        </tr>

        </thead>
        <tbody>
        <?php if(!empty($this->list) && is_array($this->list)) { ?>
        <?php foreach ($this->list as $vo): ?>
            <tr class="font-small">
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= $vo['workId'] ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= $vo['workTitle'] ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= $vo['serverName'] ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= date("Y-m-d", $vo['workStarttime']) ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= date("Y-m-d", $vo['workEndtime']) ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= $vo['workPoints'] ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>"
                       class=""><?= date("Y-m-d H:i", $vo['workJointime']) ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('workinfo', array('id' => $vo['workId'])) ?>" class="">

                        <?php switch ($vo['workStatus']) {
                            case '0':
                                echo '<span class="label label-success">待处理</span>';
                                break;
                            case '1':
                                echo '<span class="label label-warning">处理中</span>';
                                break;
                            case '2':
                                echo '<span class="label label-important">已处理</span>';
                                break;
                            case '3':
                                echo '<span class="label label-info">已完成</span>';
                                break;
                            case '4':
                                echo '<span class="label label-inverse">已关闭</span>';
                                break;
                        }?>
                    </a>
                </td>

            </tr>
        <?php endforeach ?>
        <?php } ?>
        </tbody>
    </table>
</div>
<div class="row-fluid">
    {$page}
</div>