<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZendDeveloperTools',
        'ZfcBase',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'BjyAuthorize',
        'Admin',
        'Home',
        'User'
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php'),
        'config_cache_enabled' => false,
        'config_cache_key' => 'sdf987sadfs8ad9fasdf80as8df0as',
        'module_map_cache_enabled' => false,
        'module_map_cache_key' => 'l42jkl3j4lj23i4j234njh2o34hno',
        'cache_dir' =>  __DIR__.'/../data/cache/module_cache',
        )
    );
