
<h1>登陆</h1>

<?php if ($this->error): ?>
    <p class="error">
                发生错误,请看下面提示.
    </p>
<?php endif;?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('login'));
    $form->setAttribute('method', 'post');

    echo $this->form()->openTag($form);
?>

<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('member_name')); ?></dt>
<dd><?php 
echo $this->formElement($form->get('member_name'));
echo $this->formElementErrors($form->get('member_name'));
?></dd>
<dt><?php echo $this->formLabel($form->get('member_pwd')); 
?></dt>
<dd><?php 
echo $this->formElement($form->get('member_pwd'));
echo $this->formElementErrors($form->get('member_pwd'));
?></dd>
<dd><?php 
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>

<?php echo $this->form()->closeTag($form); ?>
