<style>
.control-group .is-show>label{ display:inline-table; margin-right:15px; line-height:25px; vertical-align:middle; height:25px;}
</style>
<div class="row-fluid">
    <div class="page-header">
        <h2> <?php echo $this->escapeHtml($title);?></h2>
    </div>
    <div class="row-fluid">
    <?php $form->setAttribute('action', $this->url('admin_active_class', array('action' => 'edit','id'=>$id)));
	 	  $form->prepare();
 		  echo $this->form()->openTag($form);?>
          <?php echo $this->formRow($form->get('classId'));?>
            <div class="control-group">
                <label class="control-label" for="member_name"><span class="require">*</span>咨询分类</label>
                <div class="controls">
                 <?php echo $this->formRow($form->get('className'));?>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="member_name"><span class="require">*</span>显示</label>
                <div class="controls is-show">
                	<?php echo $this->formRow($form->get('isShow'));?>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="member_name"><span class="require">*</span>排序</label>
                <div class="controls">
                	<?php echo $this->formRow($form->get('sort'));?>	
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                	  <?php echo $this->formSubmit($form->get('submit'));?>
                      <a href="<?php echo $this->url('admin_active_class',array('action'=>'index'));?>" class="btn">返回</a>
                </div>
            </div>        
 		<?php echo $this->form()->closeTag();?>
    </div>
</div>
<script>
$(function(){
	$("#active_form").validate({
		errorPlacement:function(error,element){
			error.insertAfter(element);
		},
		submitHandler:function(form){
			form.submit();
		},
		rules:{
			class_name:{
				required:true
			},
			sort:{
				number:true,
				min:0,
				max:255
			}
		},
		messages:{
			class_name:{
				required:"咨询分类不能为空"
			},
			sort:{
				number:"排序必须是0—255之间的数",
				min:"排序必须是0—255之间的数",
				max:"排序必须是0—255之间的数"
			}
		}
	});

});
</script>